version: '3.1'
services:
  mac1:
    image: zookeeper/zookeeper:latest
    restart: always
    hostname: mac1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=mac2:2888:3888 server.3=mac3:2888:3888
  mac2:
    image: zookeeper/zookeeper:latest
    restart: always
    hostname: mac2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=mac1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=mac3:2888:3888
  mac3:
    image: zookeeper/zookeeper:latest
    restart: always
    hostname: mac3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=mac1:2888:3888 server.2=mac2:2888:3888 server.3=0.0.0.0:2888:3888
networks:
  default:
    external:
      name: base_network
